# Generated by Django 5.1.7 on 2025-03-11 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
