# Generated by Django 5.1.7 on 2025-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_order_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
