# Generated by Django 5.1.7 on 2025-03-12 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_order_received_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(default='F68C0057D3', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер')], default='manager', max_length=10),
        ),
    ]
