# Generated by Django 5.1.7 on 2025-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_remove_userprofile_is_manager_organization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(default='63C11864BD', max_length=10, unique=True),
        ),
    ]
