# Generated by Django 5.1.7 on 2025-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(default='F862F292F6', max_length=10, unique=True),
        ),
    ]
