# Generated by Django 5.1.7 on 2025-03-19 19:36

import crm_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_alter_organization_code_alter_organization_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file',
            field=models.FileField(upload_to=crm_app.models.attachment_directory_path),
        ),
    ]
