# Generated by Django 5.1.7 on 2025-03-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_alter_organization_code_alter_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderattachment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderattachment',
            name='uploaded_at',
        ),
    ]
