# Generated by Django 5.1.7 on 2025-03-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_orderattachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='orderattachment',
            name='uploaded_by',
        ),
    ]
