# Generated by Django 5.1.7 on 2025-03-14 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_remove_orderattachment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.order'),
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
