# Generated by Django 5.1.7 on 2025-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_remove_order_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Индивидуал'), ('owner', 'Владелец'), ('manager', 'Менеджер')], default='individual', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number', 'organization')},
        ),
    ]
