# Generated by Django 5.1.7 on 2025-03-20 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_alter_userprofile_role_alter_order_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number', 'organization', 'created_by')},
        ),
    ]
