# Generated by Django 5.1.7 on 2025-03-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_orderattachment_order_orderattachment_uploaded_at'),
        ('crm_app', '0012_order_assigned_to_alter_order_order_number_and_more'),
    ]

    operations = [
    ]
