# Generated by Django 5.1.7 on 2025-05-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_contactmessage'),
        ('crm_app', '0013_merge_20250322_2008'),
    ]

    operations = [
    ]
