# Generated by Django 5.1.7 on 2025-05-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_merge_0013_contactmessage_0013_merge_20250322_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message_plain', models.TextField(blank=True, verbose_name='Текст письма (обычный)')),
                ('message_html', models.TextField(blank=True, verbose_name='Текст письма (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.order'),
        ),
    ]
