# Generated by Django 5.1.7 on 2025-05-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_emailbroadcast_alter_orderattachment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.order'),
        ),
    ]
