# Generated by Django 5.1.7 on 2025-05-31 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_orderattachment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complexity_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('purchased', models.BooleanField(default=False, verbose_name='Куплено')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='furniture_files/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_types', to='crm_app.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailBroadcast',
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm_app.order'),
        ),
    ]
